name: 'Windows Build'

on:
  create:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install --no-optional
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Set Version Number
        run: |
          npx replace-in-files-cli --string="##version##" --replacement="${{ steps.tagName.outputs.tag }}" "src/**/*" "scripts/**/*"
      - run: node "./scripts/version.script.js"
      - name: Build the app
        run: npm run electron:windows
      - run: node "./scripts/copy-file.js"
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: false
          files: |
            release/*.exe
